-- ============================================================
-- Game Guides — Schema Definitivo
-- ============================================================

-- Drop existentes (orden inverso a creación)
DROP TABLE IF EXISTS gg_user_sessions CASCADE;
DROP TABLE IF EXISTS gg_game_genres CASCADE;
DROP TABLE IF EXISTS gg_game_platforms CASCADE;
DROP TABLE IF EXISTS gg_genres CASCADE;
DROP TABLE IF EXISTS gg_platforms CASCADE;
DROP TABLE IF EXISTS gg_users CASCADE;
DROP TABLE IF EXISTS gg_roles CASCADE;

-- ============================================================
-- GG_Roles
CREATE TABLE IF NOT EXISTS gg_roles (
  id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(20) UNIQUE NOT NULL
);

-- ============================================================
-- GG_Users
CREATE TABLE IF NOT EXISTS gg_users (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email      VARCHAR(256) UNIQUE NOT NULL,
  google_sub VARCHAR(256) UNIQUE,
  role_id    INT NOT NULL DEFAULT 1 REFERENCES gg_roles(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_gg_users_email ON gg_users (email);
CREATE INDEX idx_gg_users_google_sub ON gg_users (google_sub);

-- ============================================================
-- GG_UserSessions
CREATE TABLE IF NOT EXISTS gg_user_sessions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES gg_users(id),
  refresh_token VARCHAR(512) UNIQUE NOT NULL,
  expires_at    TIMESTAMPTZ NOT NULL,
  is_revoked    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_gg_user_sessions_user ON gg_user_sessions (user_id);
CREATE INDEX idx_gg_user_sessions_token ON gg_user_sessions (refresh_token);

-- ============================================================
-- GG_Platforms
CREATE TABLE IF NOT EXISTS gg_platforms (
  id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(50) UNIQUE NOT NULL
);

-- ============================================================
-- GG_Genres
CREATE TABLE IF NOT EXISTS gg_genres (
  id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(50) UNIQUE NOT NULL
);

-- ============================================================
-- GG_GamePlatforms (M:N)
CREATE TABLE IF NOT EXISTS gg_game_platforms (
  game_id     INT NOT NULL,
  platform_id INT NOT NULL REFERENCES gg_platforms(id),
  PRIMARY KEY (game_id, platform_id)
);

-- ============================================================
-- GG_GameGenres (M:N)
CREATE TABLE IF NOT EXISTS gg_game_genres (
  game_id  INT NOT NULL,
  genre_id INT NOT NULL REFERENCES gg_genres(id),
  PRIMARY KEY (game_id, genre_id)
);
